apiVersion: v1
kind: Service
metadata:
  name: {{ .ServiceName }}
  namespace: services
  labels:
    app: {{ .ServiceName }}
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: {{ .ServiceName }}